### ISSUE TITLE
Filters from UI not available in pb

### ISSUE THREAD

**Issue by sebzimmermann** [parseablehq/pb#60]
I can't see my saved filters (list is empty), but there is a filter in the UI. I am using the same user for both UI and pb

![image](https://github.com/user-attachments/assets/baf06b7c-61ed-4f99-9745-6df6971ef592)

![image](https://github.com/user-attachments/assets/bda763c1-137e-4124-920d-913499dc784d)

**Comment by Koustavd18** [comment]
Hi @sebzimmermann ,
PB supports the filter created by SQL filters in parseable console. We are planning to add support for both filter types in PB soon.
Thanks
