### ISSUE TITLE
Unable to add profiles

### ISSUE THREAD

**Issue by sebzimmermann** [parseablehq/pb#61]
Fresh download of pb.

1) List profiles:
```
│ demo                           
│ url: https://demo.parseable.com
│ user: admin  
```
2) Add new profile: `pb profile add myprofile https://parseable.mydomain.net user pwd` --> No output
3) List profiles again:
```
│ demo                           
│ url: https://demo.parseable.com
│ user: admin  
```
4) Delete demo profile: `pb profile remove demo`
5) Add new profile again
6) List profiles again:
```
│ myprofile                           
│ url: https://parseable.mydomain.net
│ user: user  
```

**Comment by AdheipSingh** [comment]
FIx https://github.com/parseablehq/pb/pull/62

I still feel this might have been caused by a previous file present in  ```/Users/yourhome/Library/Application\ Support/parseable```, the previous logic had a bug which was overriding. 
Ill suggest to clean up the this file and run profile list, profile add again.

**Comment by sebzimmermann** [comment]
@AdheipSingh I'm on Ubuntu, not MacOs. The ~/.config/parseable folder did not exist prior the setup (it was the first time I downloaded `pb`).

**Comment by AdheipSingh** [comment]
![image](https://github.com/user-attachments/assets/5fc60532-f683-417a-96da-d079f5153cc2)

**Comment by nitisht** [comment]
Thanks @AdheipSingh . merging this then.
